## NXLog Linux Configuration
define ROOT /usr

Moduledir %ROOT%/lib/nxlog/modules
CacheDir   /var/lib/nxlog/data
Pidfile    /var/run/nxlog/nxlog.pid
SpoolDir   /var/lib/nxlog/data
LogFile    /var/log/nxlog/nxlog.log
LogLevel   INFO

########################
# EXTENSIONS
########################

<Extension syslog>
    Module xm_syslog
</Extension>

<Extension gelf>
    Module xm_gelf
</Extension>

########################
# INPUTS
########################

<Input kernel>
    Module im_kernel
</Input>

<Input systemd>
    Module im_systemd
</Input>

<Input devlog>
    Module im_uds
    UDS /dev/log
    FlowControl FALSE
</Input>

<Input ssh_auth>
    Module im_file
    File "/var/log/auth.log"
    ReadFromLast TRUE
    SavePos TRUE
</Input>

########################
# PROCESSOR
########################

<Processor add_ip>
    Module pm_transformer
    Exec $ip_address = "192.168.1.200"; # Change IP address to match your system !
</Processor>

########################
# OUTPUT
########################

<Output graylog_udp>
    Module om_udp
    Host 192.168.1.207 # Change IP address to match your Alloy IP !
    Port 12201
    OutputType GELF_UDP
</Output>

########################
# ROUTE (UNE SEULE)
########################

<Route r>
    Path kernel, systemd, devlog, ssh_auth => add_ip => graylog_udp
</Route>
